---
title: "SSI fellowship application"
subtitle: "Link to slides: http://bit.ly/sea-ssi-app"
author: "Sam Abbott (@seabbs)"
institute: "London School of Hygiene and Tropical Medicine"
date: ""
output:
  xaringan::moon_reader:
    css: ["default", "default-fonts", "theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = TRUE, dpi = 330, fig.align = 'center', dev = 'svg', eval = TRUE)
```

# Outline

## 1. Who am I?

## 2. Why am I applying for an SSI fellowship?

## 3. What would I do with an SSI fellowship

---
class: center, middle, inverse

# Who am I?
---

# Background

* Research Fellow in real-time modelling of infectious disease outbreaks at the London School of Hygiene and Tropical Medicine.

* PhD in infectious disease modelling focussing on the optimal usage of the BCG Tuberculosis vaccine.

* Working primarily on Covid-19 forecasting, nowcasting, and reactive real-time analysis. 

* Strong interest in open science and science as software.

---

# Current focus - 3 main categories

1. **Developing methodology** to estimate the [basic](https://wellcomeopenresearch.org/articles/5-17/v1) and [effective](https://wellcomeopenresearch.org/articles/5-112/v2) reproduction (Rt) of Covid-19 and provide short term forecasts of key indicators (cases, hospital admissions, deaths, hospital bed usage etc.). 

2. **Deploying this methodology** as [software](https://epiforecasts.io/EpiNow2/) for use by others and by [ourselves in collaboration with the Met office](https://epiforecasts.io/covid/)<sup>1</sup>. Software used by the WHO, ECDC, and [several groups supporting other governments](https://elifesciences.org/articles/58785). Nowcasts/Forecasts used by the CDC, WHO, UK Government, ECDC etc.

3. **[Real-time analysis](https://scholar.google.co.uk/citations?hl=en&user=GqZm90IAAAAJ&view_op=list_works&sortby=pubdate) used by policy makers (SPI-M, SAGE, NERVTAG):** <sup>2</sup>

  * Weekly estimates of the effective reproduction number, current infections and forecasts/projections of future admissions etc.
  * Developments in the epidemic, for example tracking nosocomial transmission in April 2020.
  * The increase in transmissibility and severity measures of the [B.1.1.7 variant](https://github.com/epiforecasts/covid19.sgene.utla.rt).

.footnote[
  [1] [https://epiforecasts.io/covid/](https://epiforecasts.io/covid/)
  [2] [http://bit.ly/sea-scholar](http://bit.ly/sea-scholar)
]
---
class: center, middle, inverse

Why am I applying for an SSI fellowship?
 
---

# Why am I applying for an SSI fellowship?

* The Covid-19 pandemic has highlighted the need for combining robust software engineering with epidemological knowledge. 

* Many of the real time analysis projects from the beginning of the pandemic have been shuttered, likely due to technical debt.

* Most of the forecasts that are used by policy makers come from models that are closed source or not fully documented/supported making them only open source in theory.

* Many researchers lack the skills required to make their methods open source and there is little incentive to do so. 

* Research software engineering when considered at all is thought about as packaging of already complete research work rather than a truly integrated part of the process. 

---
class: center, middle, inverse

In trying to respond to the Covid-19 pandemic I have realised that I simply do not have the software engineering skills required to do so effectively and that this is a systemic problem in infectious disease modelling that hampers our ability to provide advice to policy makers.

---
class: center, middle, inverse

# What would I do with the fellowship?

---

# Personal 

* Use the SSI network to enhance my own software engineering skills so I can more effectively do my work. 

* In particular, I would like to expand beyond the silo of R knowledge into the wider community of practice. Infectious disease modelling is generally R centric and I feel this means that innovations from other fields are missed. 

* Use some of the fellowship funding for skills training (ideally a Python software development course) and potentially funds for conference travel (such as the Stan conference).

---

# Community

* Currently in the process of setting up a software engineering discussion group within LSHTM. Fellowship funding would be a great way to provide customised training to this group many of whom are transitioning from more theoretical areas of research. 

* Interested in potentially highlighting some of the key lessons learnt from the Covid-19 pandemic on the importance of software engineering in research using a short professional animation combined with a blog post. Fellowship funding could be used for this. 

* Advocate for researchers to consider their work as software rather than as a step towards a peer reviewed paper.

* Strongly advocate for RSEs to be hired within LSHTM and in the wider infectious disease modelling community.
---
class: inverse

# Summary

* Researching real time analysis methods for infectious diseases. Focussing on the Covid-19 pandemic.

* Applying as the response from the infectious disease modelling community to the pandemic has shown the impact of not having software engineering skills available.

* I would use the fellowship to enhance my own knowledge, to advocate for RSEs in infectious disease modelling, support developing a community of practice at LSHTM, and potentially to summarise some of the lessons on the importance of research engineering learnt from the Covid-19 pandemic using a professional animation.
